"""add username to users

Revision ID: 18223a19a486
Revises: 816df821bd9b
Create Date: 2026-10-03 15:09:42.148020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18223a19a486'
down_revision: Union[str, Sequence[str], None] = '816df821bd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True), schema='app')
    op.create_index(op.f('ix_app_users_username'), 'users', ['username'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_users_username'), table_name='users', schema='app')
    op.drop_column('users', 'username', schema='app')
    # ### end Alembic commands ###
