"""add retired_usernames

Revision ID: de04f183178e
Revises: 18223a19a486
Create Date: 2026-10-03 15:19:41.266565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de04f183178e'
down_revision: Union[str, Sequence[str], None] = '18223a19a486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retired_usernames',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retired_usernames', schema='app')
    # ### end Alembic commands ###
